### PR TITLE
Fix long callchains in MachineShopSimulator

### LINKED ISSUE #2: Long call chains in the MachineShopSimulator class
There are several long call chains in MSS that can be extracted into methods. These methods may even be moved elsewhere.

### PR DESCRIPTION
**Pull request by JakePeterson7**
## Description

This PR is meant to fix long call chains that we saw in MachineShopSimulator and also make the class easier to read and understand. I've extracted several methods, some of which got moved into other classes. 

## Related Issue

This PR is addressing issues #1 and #2. It works a little bit towards solving issue #3.

## Motivation and Context

My primary goal here was to make the MachineShopSimulator class smaller and more readable. To do this I've created new methods to replace the long call chains that were there. 

I saw the Long Call Chain smell particularly in the Machine Shop Simulator class.

See issues #1, #2, and #3 for additional information about the smells addressed.

## Smell impact

This is decreasing the size of MachineShopSimulator and improves its readability.

While doing this I realized just how confusing some of the methods in the class were. In places I feel that additional commenting 
on logic could help fix this. Another thing to do could be to extract some of the logic into functions.

## Testing & Screenshots:

CoverageReport
- [X ] All new and existing tests passed.

### CODE REVIEW

File: src/applications/Job.java [hunk 1]
```diff
@@ -50,4 +50,8 @@ public int getId() {
         return id;
     }
 
+	void putTaskOnMachineQueue(MachineShopSimulator machineShopSimulator, int p) {
```
Comment (NicMcPhee) [inline src/applications/Job.java]: Aren't you putting a _Job_ on the queue here? Feels like the name of the method might be:

```suggestion
	void putJobOnMachineQueue(MachineShopSimulator machineShopSimulator, int p) {
```

File: src/applications/MachineShopSimulator.java [hunk 2]
```diff
@@ -15,7 +15,7 @@
     private int numMachines; // number of machines
     private int numJobs; // number of jobs
     private EventList eList; // pointer to event list
-    private Machine[] machine; // array of machines
+    Machine[] machine; // array of machines
```
Comment (NicMcPhee) [inline src/applications/MachineShopSimulator.java]: In general you don't want to be making `private` things non-private unless there's a clear reason to do so. Is there a reason you're doing that here?

**Review by smit9025 — APPROVED** [review]
Commit messages are clear enough to understand what is going on. Not a whole lot of information beyond that. For reducing the long call chain smell extracting them into their own methods seems like a good idea. I just wonder if having many methods created from extracting long call chains is a smell itself, and doesn't just represent a need to remove the middleman. I don't currently have any suggestions.

File: src/applications/MachineShopSimulator.java [hunk 3]
```diff
@@ -86,22 +89,30 @@ private void setUpJobs(SimulationSpecification specification) {
         // input the jobs
         Job theJob;
         for (int i = 1; i <= specification.getNumJobs(); i++) {
-            int tasks = specification.getJobSpecifications(i).getNumTasks();
+            int tasks = Task.getNumTasks(specification, i);
```
Comment (NicMcPhee) [inline src/applications/MachineShopSimulator.java:92]: I'm not sure I understand why you're moving from methods attached to object (`specification.getJobSpecifications(i)`) to static methods (`Task.getNumTasks(…)`). I'm not sure I _object_, but I'm definitely not sure where you're headed with this and would love to hear more.

File: src/applications/MachineShopSimulator.java [hunk 4]
```diff
@@ -86,22 +89,30 @@ private void setUpJobs(SimulationSpecification specification) {
...
-            int tasks = specification.getJobSpecifications(i).getNumTasks();
+            int tasks = Task.getNumTasks(specification, i);
             int firstMachine = 0; // machine for first task
 
             // create the job
             theJob = new Job(i);
             for (int j = 1; j <= tasks; j++) {
-                int theMachine = specification.getJobSpecifications(i).getSpecificationsForTasks()[2*(j-1)+1];
-                int theTaskTime = specification.getJobSpecifications(i).getSpecificationsForTasks()[2*(j-1)+2];
+                int theMachine = getMachineNumber(specification, i, j);
```
Comment (NicMcPhee) [inline src/applications/MachineShopSimulator.java:97]: Nice!

File: src/applications/MachineShopSimulator.java [hunk 5]
```diff
@@ -86,22 +89,30 @@ private void setUpJobs(SimulationSpecification specification) {
...
                 if (j == 1)
                     firstMachine = theMachine; // job's first machine
                 theJob.addTask(theMachine, theTaskTime); // add to
             } // task queue
-            machine[firstMachine].getJobQ().put(theJob);
+            theJob.putTaskOnMachineQueue(this, firstMachine);
         }
     }
 
+    private int getTaskTime(SimulationSpecification specification, int i, int j) {
```
Comment (NicMcPhee) [inline src/applications/MachineShopSimulator.java:107]: These are both very nice new functions.

File: src/applications/Task.java [hunk 6]
```diff
@@ -19,4 +19,7 @@ public int getMachine() {
     public int getTime() {
         return time;
     }
+    public static int getNumTasks(SimulationSpecification specification, int i) {
```
Comment (NicMcPhee) [inline src/applications/Task.java:22]: This makes me wonder if what you want is a `JobSpecification` class that allows you to ask a instance of that class how many tasks it has? 🤔

**Review by NicMcPhee — CHANGES_REQUESTED** [review]
There are parts of this where I'm a little confused and would like to learn more (see my specific comments). The two things that stand out are:

* Making things that used to be `private` not private anymore.
* Introducing a static method in `Task`.

File: src/applications/MachineShopSimulator.java (hunk 2 above)
Comment (JakePeterson7) [reply src/applications/MachineShopSimulator.java]: No I don't think there is. I think that a refactoring tool may have changed this and I didn't notice? Changing it back to private.

Comment (JakePeterson7) [reply src/applications/MachineShopSimulator.java]: Update: I had made this non-private as it is being used in the Job class now.

File: src/applications/Job.java (hunk 1 above)
Comment (JakePeterson7) [reply src/applications/Job.java]: I agree.

File: src/applications/MachineShopSimulator.java (hunk 2 above)
Comment (JakePeterson7) [reply src/applications/MachineShopSimulator.java]: Another update after confusion: this is now private with a getter that is used in the method in the Job class.

File: src/applications/Task.java (hunk 6 above)
Comment (JakePeterson7) [reply src/applications/Task.java:22]: This will likely be something I will be addressing in the future. I agree that this doesn't seem to be in the right place.
